config/routes.rb
Feedback::Application.routes.draw do

  resources :gifts

  root :to => 'home#index'
  resources :karma_items
  resources :appreciations
  resources :people

end

app/models/appreciation.rb
class Appreciation < ActiveRecord::Base
  attr_accessible :description, :karma, :name, :from_person_id, :to_person_id
  
  belongs_to :person
end

app/models/gift.rb
class Gift < ActiveRecord::Base
  attr_accessible :name, :points
end

app/models/karma_item.rb
class KarmaItem < ActiveRecord::Base
  attr_accessible :name, :points
end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :name
  has_many :appreciations  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/appreciations_controller.rb
class AppreciationsController < ApplicationController
  # GET /appreciations
  # GET /appreciations.json
  def index
    @appreciations = Appreciation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @appreciations }
    end
  end

  # GET /appreciations/1
  # GET /appreciations/1.json
  def show
    @appreciation = Appreciation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @appreciation }
    end
  end

  # GET /appreciations/new
  # GET /appreciations/new.json
  def new
    @appreciation = Appreciation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @appreciation }
    end
  end

  # GET /appreciations/1/edit
  def edit
    @appreciation = Appreciation.find(params[:id])
  end

  # POST /appreciations
  # POST /appreciations.json
  def create
    @appreciation = Appreciation.new(params[:appreciation])

    respond_to do |format|
      if @appreciation.save
        format.html { redirect_to @appreciation, notice: 'Appreciation was successfully created.' }
        format.json { render json: @appreciation, status: :created, location: @appreciation }
      else
        format.html { render action: "new" }
        format.json { render json: @appreciation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /appreciations/1
  # PUT /appreciations/1.json
  def update
    @appreciation = Appreciation.find(params[:id])

    respond_to do |format|
      if @appreciation.update_attributes(params[:appreciation])
        format.html { redirect_to @appreciation, notice: 'Appreciation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @appreciation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appreciations/1
  # DELETE /appreciations/1.json
  def destroy
    @appreciation = Appreciation.find(params[:id])
    @appreciation.destroy

    respond_to do |format|
      format.html { redirect_to appreciations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  def index
    @gifts = Gift.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gifts }
    end
  end

  def show
    @gift = Gift.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gift }
    end
  end

  def new
    @gift = Gift.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gift }
    end
  end

  def edit
    @gift = Gift.find(params[:id])
  end

  def create
    @gift = Gift.new(params[:gift])

    respond_to do |format|
      if @gift.save
        format.html { redirect_to @gift, notice: 'Gift was successfully created.' }
        format.json { render json: @gift, status: :created, location: @gift }
      else
        format.html { render action: "new" }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @gift = Gift.find(params[:id])

    respond_to do |format|
      if @gift.update_attributes(params[:gift])
        format.html { redirect_to @gift, notice: 'Gift was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @gift = Gift.find(params[:id])
    @gift.destroy

    respond_to do |format|
      format.html { redirect_to gifts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index		
	end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end

  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appreciations_helper.rb
module AppreciationsHelper
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/appreciations/_form.html.erb
<%= form_for(@appreciation) do |f| %>
  <% if @appreciation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appreciation.errors.count, "error") %> prohibited this appreciation from being saved:</h2>

      <ul>
      <% @appreciation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :karma %><br />
    <%= f.number_field :karma %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appreciations/edit.html.erb
<h1>Editing appreciation</h1>

<%= render 'form' %>

<%= link_to 'Show', @appreciation %> |
<%= link_to 'Back', appreciations_path %>

app/views/appreciations/index.html.haml
%h3
  Appreciations
%table.table.table-striped.table-bordered.datatable
  %thead
    %tr
      %th Photo
      %th Name
      %th Karma
      %th Description
      %th Edit
  %tbody
    %tr
      %td Photo
      %td Cookie
      %td 2
      %td Cookie is awesome
      %td 
        %a{"href"=>"#"}
          Edit

app/views/appreciations/new.html.erb
<h1>New appreciation</h1>

<%= render 'form' %>

<%= link_to 'Back', appreciations_path %>

app/views/appreciations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @appreciation.user_id %>
</p>

<p>
  <b>Description:</b>
  <%= @appreciation.description %>
</p>

<p>
  <b>Name:</b>
  <%= @appreciation.name %>
</p>

<p>
  <b>Karma:</b>
  <%= @appreciation.karma %>
</p>


<%= link_to 'Edit', edit_appreciation_path(@appreciation) %> |
<%= link_to 'Back', appreciations_path %>

app/views/gifts/_form.html.haml
= form_for @gift do |f|
  -if @gift.errors.any?
    #error_explanation
      %h2= "#{pluralize(@gift.errors.count, "error")} prohibited this gift from being saved:"
      %ul
        - @gift.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :points
    = f.number_field :points
  .actions
    = f.submit 'Save'

app/views/gifts/edit.html.haml
%h1 Editing gift

= render 'form'

= link_to 'Show', @gift
\|
= link_to 'Back', gifts_path

app/views/gifts/index.html.haml
%h1 Listing gifts

%table
  %tr
    %th Name
    %th Points
    %th
    %th
    %th

  - @gifts.each do |gift|
    %tr
      %td= gift.name
      %td= gift.points
      %td= link_to 'Show', gift
      %td= link_to 'Edit', edit_gift_path(gift)
      %td= link_to 'Destroy', gift, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Gift', new_gift_path

app/views/gifts/new.html.haml
%h1 New gift

= render 'form'

= link_to 'Back', gifts_path

app/views/gifts/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @gift.name
%p
  %b Points:
  = @gift.points

= link_to 'Edit', edit_gift_path(@gift)
\|
= link_to 'Back', gifts_path

app/views/layouts/_navigation.html.haml
%header.navbar.navbar-fixed-top
  .navbar-inner
    .container-fluid
      .row-fluid
      %a.brand{"href"=>"#{root_path}"}
        %img{"src"=>"/assets/Logo-20px-transparent.png","alt"=>"Feedback"}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %meta{:name=>"google-site-verification", :content=>"L_EsKCr-S8gJ4Vtp3JVueg18xy-EIeXUGwkv3Z1A-mI"}
    %title= content_for?(:title) ? yield(:title) : "Feedback"
    %meta{:content => "", :name => "description"}
    %meta{:name=>""}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body
    = render 'layouts/navigation'
    #main{:role => "main"}
      .container-fluid
        .content
          .row-fluid
            .span12
              - flash.each do |name, msg|
                %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
                  %a.close{"data-dismiss" => "alert"} ×
                  = msg
              = yield
          %footer

app/views/layouts/navigation.html.haml
%header.navbar.navbar-fixed-top
  .navbar-inner
    .container-fluid
      .row-fluid
      %a.brand{"href"=>"#{root_path}"}
        %img{"src"=>"/assets/indix_logo.png","alt"=>"Cosmos"}

      %ul.nav
        - if user_signed_in?
          %form.navbar-search
            %input.search-query.span3#cosmos-search{"type"=>"text","placeholder"=>"Search"}
        - else
          %li
            = link_to 'Login with Indix.com', user_omniauth_authorize_path(:google_apps)

      - if user_signed_in?    
        %ul.nav.pull-right
          %li
            %a{"href"=>"#"}
              #{current_user.name}
          %li
            %a{"href"=>"#{destroy_user_session_path}",:method=>'delete'}
              Logout

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.haml
%h3
	People
%table.table.table-striped.table-bordered.datatable
	%thead
		%tr
			%th Avatar
			%th Name
			%th Karma
			%th Action
	%tbody
		%tr
			%td Avatar
			%td User 1
			%td 100
			%td 
				%a{"href"=>"#"}
					Edit

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @person.name %>
</p>


<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>